### ISSUE TITLE
Something went wrong in android 

### ISSUE THREAD

**Issue by ramisalem** [mateioprea/react-native-intercom#7]
Hello thanks for such an awesome package

I have an issue with android when I try to display the intrcome massenger page

here is what I did 
// in App.js 

```
 Intercom.setApiKey(
	Platform.OS === 'android'
		? intrcomAndroidApiKey
		:  intrcomIosApiKey ,
    intrcomAppId
);
``` 
```
// in another page I called the belw methods in  onPress event 

Intercom.registerUserWithIdentifier('user@gmail.com', '008990809');
Intercom.presentMessenger();  
```

![photo_2020-10-29_14-29-29](https://user-images.githubusercontent.com/25037017/97547027-462c7c80-19f3-11eb-9f70-a426d1dfb8ba.jpg)

**Comment by mateioprea** [comment]
Sorry, this package doesn't work with expo

**Comment by ramisalem** [comment]
It is not an expo app, I am getting it working on IOS, I am gettting this issue in android only

**Comment by saagarbhagwat** [comment]
Im also having same issue.And Im not using the expo.

**Comment by mateioprea** [comment]
Using latest build gradle version in your build.gradle fixed the issue. This is not an issue with the package, it’s an issue with your app config
