### ISSUE TITLE
How to disable notifiactions in IOS 

### ISSUE THREAD

**Issue by ramisalem** [mateioprea/react-native-intercom#8]
Hi @mateioprea, 

I am using expo-notifiactions in my react-native app  and after installing this pacakge it brokes expo-notfications
I tried to disalbe   Intercom Push Notifications by running npx intercom-link --disable-notification-link  without any lack 

Thanks in advance

**Comment by mateioprea** [comment]
Hi, this package doesn't work with expo. Sorry.

**Comment by ramisalem** [comment]
It is not expo app, It is Pure React Native but I use expo-notifications, so it wont work with expo-notifications ?

**Comment by mateioprea** [comment]
Actually it doesn’t work, sorry
